# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from aptos_sdk.api_client import ApiClient
from aptos_sdk.api.general_api_endpoints.get_ledger_info import GetLedgerInfo
from aptos_sdk.api.general_api_endpoints.spec import Spec


class GeneralApi(
    GetLedgerInfo,
    Spec,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
