# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from aptos_sdk.api_client import ApiClient
from aptos_sdk.api.transactions_api_endpoints.encode_submission import EncodeSubmission
from aptos_sdk.api.transactions_api_endpoints.get_account_transactions import GetAccountTransactions
from aptos_sdk.api.transactions_api_endpoints.get_transaction_by_hash import GetTransactionByHash
from aptos_sdk.api.transactions_api_endpoints.get_transaction_by_version import GetTransactionByVersion
from aptos_sdk.api.transactions_api_endpoints.get_transactions import GetTransactions
from aptos_sdk.api.transactions_api_endpoints.simulate_transaction import SimulateTransaction
from aptos_sdk.api.transactions_api_endpoints.submit_transaction import SubmitTransaction


class TransactionsApi(
    EncodeSubmission,
    GetAccountTransactions,
    GetTransactionByHash,
    GetTransactionByVersion,
    GetTransactions,
    SimulateTransaction,
    SubmitTransaction,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
