# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "Aptos Python SDK"
VERSION = "0.0.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.15",
  "certifi",
  "python-dateutil",
  "frozendict >= 2.0.3",
]

setup(
    name=NAME,
    version=VERSION,
    description="Aptos Node API",
    author="Aptos Labs",
    author_email="team@openapitools.org",
    url="https://github.com/aptos-labs/aptos-core/tree/main/ecosystem/python/sdk",
    keywords=["OpenAPI", "OpenAPI-Generator", "Aptos Node API"],
    python_requires=">=3.9",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache 2.0",
    long_description="""\
    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501
    """
)
