# This file is loaded in by Forge test runner at runtime and templated
# These are meant to be Forge-specific overrides. If you have a new config, please add
# it to the base helm values at terraform/helm/aptos-node/values.yaml

# the number of validators to deploy
numValidators: {num_validators}

# the total number of fullnode groups to deploy
# this number must be less than numValidators
numFullnodeGroups: {num_fullnodes}

imageTag: {image_tag}
chain:
  era: {era}

# disable NetworkPolicy and HAProxy so test can hit validators directly
validator:
  enableNetworkPolicy: false
  rust_log: debug
haproxy:
  enabled: {enable_haproxy}

fullnode:
  # at most one VFN per validator, depending on numFullnodeGroups
  groups:
  - name: fullnode
    replicas: 1
  rust_log: debug

# make all services internal ClusterIP and open all ports
service:
  validator:
    external:
      type: "ClusterIP"
    enableRestApi: true
    enableMetricsPort: true

  fullnode:
    external:
      type: "ClusterIP"
    enableRestApi: true
    enableMetricsPort: true

labels:
  forge-namespace: {namespace}
  forge-image-tag: {image_tag}
