# This file is loaded in by Forge test runner at runtime and templated
# These are meant to be Forge-specific overrides. If you have a new config, please add
# it to the base helm values at terraform/helm/genesis/values.yaml

imageTag: {image_tag}

chain:
  era: {era}
  # expect the root key without 0x prefix
  root_key: 0x{root_key}

genesis:
  numValidators: {num_validators}
  validator:
    # use non-HAProxy service for validator AptosNet in genesis
    internal_host_suffix: {validator_internal_host_suffix}
  fullnode:
    # use non-HAProxy service for fullnode AptosNet in genesis
    internal_host_suffix: {fullnode_internal_host_suffix}

labels:
  forge-namespace: {namespace}
  forge-image-tag: {image_tag}
