chain:
  name: testnet
  era: 1
  chain_id: 4
  root_key: '0x5243ca72b0766d9e9cbf2debf6153443b01a1e0e6d086c7ea206eaf6f8043956'
  min_stake: 0
  max_stake: 100000
  epoch_duration_secs: 300 # 5 minutes
  recurring_lockup_duration_secs: 86400 # 1 day
  # instead of specifying "initial_lockup_timestamp", just take the delta between
  # the current timestamp
  initial_lockup_duration: 1d
  min_price_per_gas_unit: 1
  allow_new_validators: false

imageTag: testnet

genesis:
  image:
    repo: aptoslabs/tools
    tag:
    pullPolicy: IfNotPresent
  # Number of validators to include in genesis
  numValidators: 1
  # Controls whether to use public DNS as created by aptos-node helm chart
  # If not using public DNS, assumes the validators and fullnodes are using the service names
  # from aptos-node helm chart
  username_prefix: aptos-node
  domain:
  validator:
    enable_onchain_discovery: false
    internal_host_suffix: validator-lb
  fullnode:
    enable_onchain_discovery: true
    internal_host_suffix: fullnode-lb
  # The path or move modules in the docker image to pull
  # Defaults to the aptos-framework in the aptoslabs/tools docker image
  moveModulesDir: /aptos-framework/move/modules

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

# LEGACY: create PodSecurityPolicy, which exists at the cluster-level
podSecurityPolicy: true

# Additional labels
labels:
