# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from aptos_sdk.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class AptosErrorCode(
    _SchemaEnumMaker(
        enum_value_to_name={
            "read_from_storage_error": "READ_FROM_STORAGE_ERROR",
            "invalid_bcs_in_storage_error": "INVALID_BCS_IN_STORAGE_ERROR",
            "bcs_serialization_error": "BCS_SERIALIZATION_ERROR",
            "invalid_start_param": "INVALID_START_PARAM",
            "invalid_limit_param": "INVALID_LIMIT_PARAM",
        }
    ),
    StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    These codes provide more granular error information beyond just the HTTP
status code of the response.
    """
    
    @classmethod
    @property
    def READ_FROM_STORAGE_ERROR(cls):
        return cls("read_from_storage_error")
    
    @classmethod
    @property
    def INVALID_BCS_IN_STORAGE_ERROR(cls):
        return cls("invalid_bcs_in_storage_error")
    
    @classmethod
    @property
    def BCS_SERIALIZATION_ERROR(cls):
        return cls("bcs_serialization_error")
    
    @classmethod
    @property
    def INVALID_START_PARAM(cls):
        return cls("invalid_start_param")
    
    @classmethod
    @property
    def INVALID_LIMIT_PARAM(cls):
        return cls("invalid_limit_param")
