# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from aptos_sdk.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class AptosError(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    This is the generic struct we use for all API errors, it contains a string
message and an Aptos API specific error code.
    """
    _required_property_names = set((
        'message',
    ))
    message = StrSchema

    @classmethod
    @property
    def error_code(cls) -> typing.Type['AptosErrorCode']:
        return AptosErrorCode
    aptos_ledger_version = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        message: message,
        error_code: typing.Union['AptosErrorCode', Unset] = unset,
        aptos_ledger_version: typing.Union[aptos_ledger_version, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'AptosError':
        return super().__new__(
            cls,
            *args,
            message=message,
            error_code=error_code,
            aptos_ledger_version=aptos_ledger_version,
            _configuration=_configuration,
            **kwargs,
        )

from aptos_sdk.model.aptos_error_code import AptosErrorCode
