# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from aptos_sdk.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class MoveFunction(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    _required_property_names = set((
        'name',
        'visibility',
        'is_entry',
        'generic_type_params',
        'params',
        'return',
    ))
    name = StrSchema

    @classmethod
    @property
    def visibility(cls) -> typing.Type['MoveFunctionVisibility']:
        return MoveFunctionVisibility
    is_entry = BoolSchema
    
    
    class generic_type_params(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['MoveFunctionGenericTypeParam']:
            return MoveFunctionGenericTypeParam
    
    
    class params(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['MoveType']:
            return MoveType
    
    
    class _return(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['MoveType']:
            return MoveType
    locals()["return"] = _return
    del locals()['_return']


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        name: name,
        visibility: visibility,
        is_entry: is_entry,
        generic_type_params: generic_type_params,
        params: params,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'MoveFunction':
        return super().__new__(
            cls,
            *args,
            name=name,
            visibility=visibility,
            is_entry=is_entry,
            generic_type_params=generic_type_params,
            params=params,
            _configuration=_configuration,
            **kwargs,
        )

from aptos_sdk.model.move_function_generic_type_param import MoveFunctionGenericTypeParam
from aptos_sdk.model.move_function_visibility import MoveFunctionVisibility
from aptos_sdk.model.move_type import MoveType
