# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from aptos_sdk.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class MultiAgentSignature(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    _required_property_names = set((
        'sender',
        'secondary_signer_addresses',
        'secondary_signers',
    ))

    @classmethod
    @property
    def sender(cls) -> typing.Type['AccountSignature']:
        return AccountSignature
    
    
    class secondary_signer_addresses(
        ListSchema
    ):
        _items = StrSchema
    
    
    class secondary_signers(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['AccountSignature']:
            return AccountSignature


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        sender: sender,
        secondary_signer_addresses: secondary_signer_addresses,
        secondary_signers: secondary_signers,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'MultiAgentSignature':
        return super().__new__(
            cls,
            *args,
            sender=sender,
            secondary_signer_addresses=secondary_signer_addresses,
            secondary_signers=secondary_signers,
            _configuration=_configuration,
            **kwargs,
        )

from aptos_sdk.model.account_signature import AccountSignature
