# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.transaction_signature_multi_ed25519_signature import TransactionSignatureMultiEd25519Signature
from openapi_client import configuration


class TestTransactionSignatureMultiEd25519Signature(unittest.TestCase):
    """TransactionSignatureMultiEd25519Signature unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
