# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.api.general_api import GeneralApi  # noqa: E501


class TestGeneralApi(unittest.TestCase):
    """GeneralApi unit test stubs"""

    def setUp(self):
        self.api = GeneralApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ledger_info(self):
        """Test case for get_ledger_info

        Get ledger info  # noqa: E501
        """
        pass

    def test_spec(self):
        """Test case for spec

        Show OpenAPI explorer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
