# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.api.transactions_api import TransactionsApi  # noqa: E501


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self):
        self.api = TransactionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_encode_submission(self):
        """Test case for encode_submission

        Encode submission  # noqa: E501
        """
        pass

    def test_get_account_transactions(self):
        """Test case for get_account_transactions

        Get account transactions  # noqa: E501
        """
        pass

    def test_get_transaction_by_hash(self):
        """Test case for get_transaction_by_hash

        Get transaction by hash  # noqa: E501
        """
        pass

    def test_get_transaction_by_version(self):
        """Test case for get_transaction_by_version

        Get transaction by version  # noqa: E501
        """
        pass

    def test_get_transactions(self):
        """Test case for get_transactions

        Get transactions  # noqa: E501
        """
        pass

    def test_simulate_transaction(self):
        """Test case for simulate_transaction

        Simulate transaction  # noqa: E501
        """
        pass

    def test_submit_transaction(self):
        """Test case for submit_transaction

        Submit transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
