# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.api.accounts_api import AccountsApi  # noqa: E501


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account(self):
        """Test case for get_account

        Get account  # noqa: E501
        """
        pass

    def test_get_account_module(self):
        """Test case for get_account_module

        Get specific account module  # noqa: E501
        """
        pass

    def test_get_account_modules(self):
        """Test case for get_account_modules

        Get account modules  # noqa: E501
        """
        pass

    def test_get_account_resource(self):
        """Test case for get_account_resource

        Get specific account resource  # noqa: E501
        """
        pass

    def test_get_account_resources(self):
        """Test case for get_account_resources

        Get account resources  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
