# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.api.events_api import EventsApi  # noqa: E501


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_events_by_event_handle(self):
        """Test case for get_events_by_event_handle

        Get events by event handle  # noqa: E501
        """
        pass

    def test_get_events_by_event_key(self):
        """Test case for get_events_by_event_key

        Get events by event key  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
