# coding: utf-8

"""
    Aptos Node API

    The Aptos Node API is a RESTful API for client applications to interact with the Aptos blockchain.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.api.tables_api import TablesApi  # noqa: E501


class TestTablesApi(unittest.TestCase):
    """TablesApi unit test stubs"""

    def setUp(self):
        self.api = TablesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_table_item(self):
        """Test case for get_table_item

        Get table item  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
