name: Run Forge

on:
  # this is called from within the build-images.yaml workflow since we depend on the images having been built before
  workflow_call:
    inputs:
      GIT_SHA:
        required: false
        type: string
        description: The git SHA1 to test. If not specified, Forge will check the latest commits on the current branch
      FORGE_NAMESPACE:
        required: true
        type: string
        description: The Forge k8s namespace to be used for test. This value should manage Forge test concurrency. It may be truncated.
      FORGE_CLUSTER_NAME:
        required: false
        type: string
        default: aptos-forge-0
        description: The Forge k8s cluster to be used for test
      FORGE_RUNNER_DURATION_SECS:
        required: false
        type: string
        default: 3600
        description: Duration of the forge test run
      FORGE_RUNNER_TPS_THRESHOLD:
        required: false
        type: string
        default: 6000
        description: Minimum required avg tps to pass forge

env:
  AWS_ACCOUNT_NUM: ${{ secrets.ENV_ECR_AWS_ACCOUNT_NUM }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2
  IMAGE_TAG: ${{ inputs.GIT_SHA }}
  FORGE_ENABLED: ${{ secrets.FORGE_ENABLED }}
  FORGE_BLOCKING: ${{ secrets.FORGE_BLOCKING }}
  FORGE_CLUSTER_NAME: ${{ inputs.FORGE_CLUSTER_NAME }}
  FORGE_OUTPUT: forge_output.txt
  FORGE_REPORT: forge_report.json
  FORGE_COMMENT: forge_comment.txt
  FORGE_PRE_COMMENT: forge_pre_comment.txt
  FORGE_RUNNER_MODE: k8s
  FORGE_RUNNER_DURATION_SECS: ${{ inputs.FORGE_RUNNER_DURATION_SECS }}
  FORGE_RUNNER_TPS_THRESHOLD: ${{ inputs.FORGE_RUNNER_TPS_THRESHOLD }}
  FORGE_NAMESPACE: ${{ inputs.FORGE_NAMESPACE }}

jobs:
  forge:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        if: env.FORGE_ENABLED == 'true'
        with:
          ref: ${{ inputs.GIT_SHA }}
          # get the last 10 commits if IMAGE_TAG is not specified
          fetch-depth: env.IMAGE_TAG != null && 0 || 10
      - name: Set kubectl context
        if: env.FORGE_ENABLED == 'true'
        run: aws eks update-kubeconfig --name $FORGE_CLUSTER_NAME
      - name: Run pre-Forge checks
        if: env.FORGE_ENABLED == 'true'
        shell: bash
        env:
          FORGE_RUNNER_MODE: pre-forge
        run: |
          set +e

          source testsuite/run_forge.sh

          # export env vars for next step
          echo "FORGE_PRE_COMMENT=$FORGE_PRE_COMMENT" >> $GITHUB_ENV

          # append some GHA-specific content to the comment
          cat << EOF >> $FORGE_PRE_COMMENT
          * [Test runner output](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          * Pending test run ${{ github.run_attempt }} ${{ env.FORGE_BLOCKING == 'true' && 'is land-blocking' || 'is not land-blocking' }}
          EOF

      - name: Post pre-Forge comment
        if: env.FORGE_ENABLED == 'true' && github.event.number != null
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          header: forge-comment-${{ github.run_attempt }}
          path: ${{ env.FORGE_PRE_COMMENT }}

      - name: Run Forge
        if: env.FORGE_ENABLED == 'true'
        shell: bash
        env:
          PUSH_GATEWAY: ${{ secrets.PUSH_GATEWAY }}
          PUSH_GATEWAY_USER: ${{ secrets.PUSH_GATEWAY_USER }}
          PUSH_GATEWAY_PASSWORD: ${{ secrets.PUSH_GATEWAY_PASSWORD }}
        run: |
          set +e

          # source this script to run and get environment variables
          source testsuite/run_forge.sh

          # append some GHA-specific content to the comment
          cat << EOF >> $FORGE_COMMENT
          * [Test runner output](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          * Test run ${{ github.run_attempt }} ${{ env.FORGE_BLOCKING == 'true' && 'is land-blocking' || 'is not land-blocking' }}
          EOF

          # add github step summary as described here https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
          cat $FORGE_COMMENT >> $GITHUB_STEP_SUMMARY

          if [ "$FORGE_BLOCKING" = "true" ]; then
            exit $FORGE_EXIT_CODE
          fi

      - name: Post forge result comment
        if: env.FORGE_ENABLED == 'true' && github.event.number != null && !cancelled()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: ${{ env.FORGE_COMMENT }}
          header: forge-comment-${{ github.run_attempt }}
